"""
Project session loader — reads an existing output folder for --fix mode.
Loads session.json (saved by the prototype builder) and reconstructs
the full graph state so QA validation can run against existing files.
"""

import json
import os
from utils.display import console


SESSION_FILE = ".architect_session.json"


def save_session(project_dir: str, state: dict):
    """
    Save the full context (requirements, spec, architecture, tech stack, file list)
    to session.json inside the output project folder.
    Called by the prototype builder after writing files.
    """
    session = {
        "requirements":   state.get("requirements", ""),
        "product_spec":   state.get("product_spec"),
        "architecture":   state.get("architecture"),
        "tech_stack":     state.get("tech_stack"),
        "critique":       state.get("critique"),
    }
    session_path = os.path.join(project_dir, SESSION_FILE)
    with open(session_path, "w", encoding="utf-8") as f:
        json.dump(session, f, indent=2, default=str)  # default=str handles non-serializable objects


def load_existing_project(folder_path: str) -> dict:
    """
    Load an existing output project for --fix mode.

    Reads session.json for the design context, then walks the folder
    to reconstruct the prototype file list from disk.

    Args:
        folder_path: Absolute or relative path to the project folder
                     (e.g. 'output/Rust_Todo_App' or a full path)

    Returns:
        A dict with all state keys pre-populated:
        - requirements, product_spec, architecture, tech_stack, critique
        - prototype (with files loaded from disk)
        - qa_result = None (so QA runs fresh)

    Raises:
        FileNotFoundError: if the folder or session.json doesn't exist
        ValueError: if session.json is malformed
    """
    folder_path = os.path.abspath(folder_path)

    if not os.path.isdir(folder_path):
        raise FileNotFoundError(f"Project folder not found: {folder_path}")

    session_path = os.path.join(folder_path, SESSION_FILE)
    if not os.path.exists(session_path):
        raise FileNotFoundError(
            f"No session file found at: {session_path}\n"
            "This folder may not have been generated by this tool.\n"
            "Run without --fix to generate a fresh project."
        )

    # Load session context
    try:
        with open(session_path, "r", encoding="utf-8") as f:
            session = json.load(f)
    except json.JSONDecodeError as e:
        raise ValueError(f"Corrupted session file: {e}")

    # Read all project files from disk
    files = []
    for root, dirs, filenames in os.walk(folder_path):
        # Skip hidden dirs, __pycache__, target (Rust build artifacts)
        dirs[:] = [
            d for d in dirs
            if not d.startswith(".") and d not in ("__pycache__", "target", "node_modules", ".git")
        ]
        for filename in filenames:
            if filename == SESSION_FILE:
                continue  # Skip the session file itself
            abs_path = os.path.join(root, filename)
            rel_path = os.path.relpath(abs_path, folder_path).replace("\\", "/")
            try:
                with open(abs_path, "r", encoding="utf-8", errors="replace") as f:
                    content = f.read()
                files.append({
                    "path": rel_path,
                    "content": content,
                    "description": f"Existing file loaded from disk",
                })
            except Exception:
                pass  # Skip unreadable files (binaries, etc.)

    # Build the prototype state from disk
    prototype = {
        "readme": next(
            (f["content"] for f in files if f["path"].lower() == "readme.md"),
            "# Project\n\nLoaded from existing output folder."
        ),
        "files": [f for f in files if f["path"].lower() != "readme.md"],
        "output_dir": folder_path,
    }

    console.print(f"  [dim]Loaded {len(files)} files from {folder_path}[/]")

    return {
        "requirements":  session.get("requirements", ""),
        "product_spec":  session.get("product_spec"),
        "architecture":  session.get("architecture"),
        "tech_stack":    session.get("tech_stack"),
        "critique":      session.get("critique"),
        "prototype":     prototype,
        "qa_result":     None,   # Always re-run QA
        "revision_count": 0,
        "messages":      [],
        "current_phase": "Fix Mode",
        "next_agent":    "",
        "auto_mode":     True,
        "fix_mode":      True,
    }
